name: AIL 요청
description: AIL 형식으로 작업 요청을 생성합니다
title: "[AIL] "
labels: ["ail-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## AIL 요청 폼
        자연어 논의는 댓글에서, 실행 지시는 아래 AIL 형식으로 작성해주세요.

  - type: dropdown
    id: case_type
    attributes:
      label: CASE 유형
      description: 작업 유형을 선택하세요
      options:
        - CASE-A: 기능 추가/변경
        - CASE-B: 버그 수정
        - CASE-C: 리팩토링/성능 개선
        - CASE-D: 문서/설정 변경
        - CASE-E: 긴급 핫픽스
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 작업 우선순위를 선택하세요
      options:
        - P0: 즉시 (영업일 기준 당일)
        - P1: 긴급 (1-2일)
        - P2: 보통 (3-5일)
        - P3: 여유 (1주 이상)
    validations:
      required: true

  - type: input
    id: owner
    attributes:
      label: 담당자
      description: 작업 담당자 (GitHub ID 또는 이름)
      placeholder: "@username 또는 코미/재미/루미/코드"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: "[CONTEXT] 배경 및 목표"
      description: 이 작업이 필요한 배경과 달성 목표
      placeholder: |
        - 배경:
        - 목표:
    validations:
      required: true

  - type: textarea
    id: instruction
    attributes:
      label: "[INSTRUCTION] 구체적 지시사항"
      description: 수행해야 할 작업을 단계별로 작성
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: "[CONSTRAINTS] 제약조건"
      description: 지켜야 할 제약사항, 금지사항
      placeholder: |
        - 기존 API 호환성 유지
        - 개인정보 GitHub 저장 금지
    validations:
      required: false

  - type: textarea
    id: done_when
    attributes:
      label: "[DONE_WHEN] 완료 조건"
      description: 이 작업이 완료되었다고 볼 수 있는 조건
      placeholder: |
        - [ ] 테스트 통과
        - [ ] 코드 리뷰 완료
        - [ ] 배포 확인
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: 관련 링크
      description: 참고 문서, Drive 링크, 기존 Issue 등
      placeholder: |
        - Drive:
        - Notion:
        - 관련 Issue: #
    validations:
      required: false

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: 확인 사항
      options:
        - label: 자연어 논의는 댓글에서, 실행 지시는 AIL 형식으로 작성했습니다.
          required: true
        - label: 개인정보/민감 데이터를 GitHub에 직접 포함하지 않았습니다.
          required: true
