/**
 * 파이프라인 실행 스크립트
 *
 * Weekly Summary 파이프라인을 실행하여 주간 리포트를 생성합니다.
 *
 * 실행: npx ts-node scripts/run-pipeline.ts
 * 또는: npm run pipeline:weekly
 */

import * as fs from "fs";
import * as path from "path";

// ===== 설정 =====
const CONFIG = {
  pipelineName: "weekly-summary",
  outputDir: path.join(__dirname, "..", "reports", "weekly"),
  templatesDir: path.join(__dirname, "..", "reports", "templates"),
  agentsDir: path.join(__dirname, "..", "claude", "agents"),
};

// ===== 타입 정의 =====
interface PipelineInput {
  conversations: string;
  dateRange: {
    start: string;
    end: string;
  };
  team?: string;
}

interface SummaryResult {
  highlights: string[];
  projectStatus: Array<{
    project: string;
    status: string;
    progress: number;
  }>;
  nextWeek: string[];
}

interface Decision {
  id: number;
  content: string;
  participants: string[];
  impact: "high" | "medium" | "low";
}

interface ActionItem {
  id: number;
  task: string;
  assignee: string | null;
  deadline: string | null;
  priority: "high" | "medium" | "low";
}

interface PipelineOutput {
  summary: SummaryResult;
  decisions: Decision[];
  actions: ActionItem[];
  generatedAt: string;
}

// ===== 유틸리티 함수 =====
function getDateString(): string {
  return new Date().toISOString().split("T")[0];
}

function getWeekRange(): { start: string; end: string } {
  const now = new Date();
  const dayOfWeek = now.getDay();
  const start = new Date(now);
  start.setDate(now.getDate() - dayOfWeek - 6); // 지난 주 월요일
  const end = new Date(now);
  end.setDate(now.getDate() - dayOfWeek); // 지난 주 일요일

  return {
    start: start.toISOString().split("T")[0],
    end: end.toISOString().split("T")[0],
  };
}

// ===== 에이전트 실행 함수 =====

/**
 * Stage 1: Summarizer 에이전트 실행
 */
async function runSummarizer(text: string): Promise<SummaryResult> {
  console.log("📝 Stage 1: Summarizer 실행 중...");

  // 실제 구현에서는 Claude API 호출
  // 여기서는 구조만 정의
  const prompt = `
다음 대화를 주간 요약 형식으로 정리해주세요.

원문:
${text}
  `;

  // TODO: Claude API 호출
  // const response = await callClaude(prompt);

  // 임시 반환 (실제 구현 시 API 응답 파싱)
  return {
    highlights: [],
    projectStatus: [],
    nextWeek: [],
  };
}

/**
 * Stage 2: Decision Extractor 에이전트 실행
 */
async function runDecisionExtractor(text: string): Promise<Decision[]> {
  console.log("✅ Stage 2: Decision Extractor 실행 중...");

  const prompt = `
다음 대화에서 결정 사항을 추출해주세요.

원문:
${text}
  `;

  // TODO: Claude API 호출
  return [];
}

/**
 * Stage 3: Action Extractor 에이전트 실행
 */
async function runActionExtractor(text: string): Promise<ActionItem[]> {
  console.log("📋 Stage 3: Action Extractor 실행 중...");

  const prompt = `
다음 대화에서 Action Item을 추출해주세요.

원문:
${text}
  `;

  // TODO: Claude API 호출
  return [];
}

// ===== 리포트 생성 =====

/**
 * 파이프라인 결과를 마크다운 리포트로 변환
 */
function generateReport(
  input: PipelineInput,
  output: PipelineOutput
): string {
  const { summary, decisions, actions, generatedAt } = output;

  const priorityEmoji = {
    high: "🔴",
    medium: "🟡",
    low: "🟢",
  };

  let report = `# 📊 주간 리포트

> 기간: ${input.dateRange.start} ~ ${input.dateRange.end}
> 팀: ${input.team || "전체"}
> 생성일: ${generatedAt}

---

## 📋 이번 주 하이라이트

${summary.highlights.map((h) => `- ${h}`).join("\n") || "- (내용 없음)"}

---

## 📁 프로젝트별 진행 상황

| 프로젝트 | 상태 | 진행률 |
|---------|------|-------|
${
  summary.projectStatus
    .map((p) => `| ${p.project} | ${p.status} | ${p.progress}% |`)
    .join("\n") || "| - | - | - |"
}

---

## ✅ 결정 사항

| # | 결정 내용 | 관련자 | 영향도 |
|---|----------|-------|-------|
${
  decisions
    .map(
      (d) =>
        `| ${d.id} | ${d.content} | ${d.participants.join(", ")} | ${priorityEmoji[d.impact]} ${d.impact} |`
    )
    .join("\n") || "| - | - | - | - |"
}

---

## 📝 Action Items

| # | 업무 | 담당자 | 기한 | 우선순위 |
|---|------|-------|------|---------|
${
  actions
    .map(
      (a) =>
        `| ${a.id} | ${a.task} | ${a.assignee || "TBD"} | ${a.deadline || "-"} | ${priorityEmoji[a.priority]} ${a.priority} |`
    )
    .join("\n") || "| - | - | - | - | - |"
}

---

## 📅 다음 주 계획

${summary.nextWeek.map((n) => `- ${n}`).join("\n") || "- (내용 없음)"}

---

*🤖 Generated by Weekly Summary Pipeline*
*📁 파일: reports/weekly/weekly-${generatedAt}.md*
`;

  return report;
}

/**
 * 리포트 파일 저장
 */
function saveReport(content: string, date: string): string {
  const filename = `weekly-${date}.md`;
  const filepath = path.join(CONFIG.outputDir, filename);

  // 디렉토리 확인
  if (!fs.existsSync(CONFIG.outputDir)) {
    fs.mkdirSync(CONFIG.outputDir, { recursive: true });
  }

  fs.writeFileSync(filepath, content, "utf-8");
  return filepath;
}

// ===== 메인 파이프라인 =====

/**
 * Weekly Summary 파이프라인 실행
 */
async function runWeeklySummaryPipeline(
  input: PipelineInput
): Promise<string> {
  console.log("🚀 Weekly Summary 파이프라인 시작");
  console.log(`📅 기간: ${input.dateRange.start} ~ ${input.dateRange.end}`);
  console.log("");

  try {
    // Stage 1: Summarizer
    const summary = await runSummarizer(input.conversations);

    // Stage 2: Decision Extractor
    const decisions = await runDecisionExtractor(input.conversations);

    // Stage 3: Action Extractor
    const actions = await runActionExtractor(input.conversations);

    // 결과 통합
    const output: PipelineOutput = {
      summary,
      decisions,
      actions,
      generatedAt: getDateString(),
    };

    // 리포트 생성
    console.log("\n📄 리포트 생성 중...");
    const report = generateReport(input, output);

    // 파일 저장
    const filepath = saveReport(report, output.generatedAt);
    console.log(`\n✅ 리포트 저장 완료: ${filepath}`);

    return filepath;
  } catch (error) {
    console.error("❌ 파이프라인 실행 실패:", error);
    throw error;
  }
}

// ===== CLI 실행 =====

async function main() {
  // 인자 파싱
  const args = process.argv.slice(2);
  const inputFile = args.find((a) => a.startsWith("--input="))?.split("=")[1];
  const team = args.find((a) => a.startsWith("--team="))?.split("=")[1];

  // 입력 데이터 준비
  let conversations = "";

  if (inputFile && fs.existsSync(inputFile)) {
    conversations = fs.readFileSync(inputFile, "utf-8");
  } else {
    // 테스트용 샘플 데이터
    conversations = `
[2024-12-23 월요일]
- API 설계 논의: REST vs GraphQL → REST로 결정
- 김개발: API 문서 작성 시작하겠습니다

[2024-12-24 화요일]
- 디자인 리뷰 완료
- 박디자인: 컴포넌트 수정 필요 (12/26까지)

[2024-12-25 수요일]
- 휴일

[2024-12-26 목요일]
- QA 테스트 시작
- 버그 3건 발견 → 이테스트가 12/27까지 수정 예정

[2024-12-27 금요일]
- MVP 배포 완료
- 다음 주 사용자 피드백 수집 예정
    `;
    console.log("⚠️ 입력 파일이 없어 샘플 데이터 사용\n");
  }

  const input: PipelineInput = {
    conversations,
    dateRange: getWeekRange(),
    team: team || "개발팀",
  };

  await runWeeklySummaryPipeline(input);
}

// 실행
main().catch(console.error);
